#
#Thu Jun 11 10:46:06 COT 2026
chrome.switches=--disable-infobars,--disable-notifications,--remote-allow-origins\=*
name=proyecto
browserName=chrome
unhandledPromptBehavior=ignore
version=
platform=ANY
