# Navegador
webdriver.driver=chrome
webdriver.chrome.driver=src/test/resources/driver/chromedriver.exe

# Proyecto
serenity.project.name=AutomatizacionVeterinaria

# Browser
serenity.use.unique.browser=false
serenity.browser.width=1600
serenity.browser.height=800

# Esperas
webdriver.wait.for.timeout=20000

# Evidencias
serenity.take.screenshots=AFTER_EACH_STEP
serenity.verbose.steps=false

# Encoding
serenity.report.encoding=UTF8
feature.file.encoding=UTF8

# Root package
serenity.test.root=co.com.veterinaria.runners

# Capabilities
serenity.driver.capabilities=name:proyecto;unhandledPromptBehavior:ignore;handlesAlerts:true

# Chrome
chrome.switches=--disable-infobars,--disable-notifications,--remote-allow-origins=*,--start-maximized,--no-sandbox,--disable-dev-shm-usage

# URL Base
webdriver.base.url=http://localhost:3000/
